// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlqb23RXVkAD1W21TvOVcnm6lL1SmA3Z4',
    appId: '1:807035683294:web:54e6659bcef9034a6b1d4f',
    messagingSenderId: '807035683294',
    projectId: 'eventify-simplified',
    authDomain: 'eventify-simplified.firebaseapp.com',
    storageBucket: 'eventify-simplified.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuPRqME8LdZYrmQJS3knFUSwoc4fJ2TpQ',
    appId: '1:807035683294:android:1c1c340466f29ce76b1d4f',
    messagingSenderId: '807035683294',
    projectId: 'eventify-simplified',
    storageBucket: 'eventify-simplified.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvu9gvH2g08k5TcbpQOd_lZctnlrZi9bE',
    appId: '1:807035683294:ios:b8cfbc46a2ac93766b1d4f',
    messagingSenderId: '807035683294',
    projectId: 'eventify-simplified',
    storageBucket: 'eventify-simplified.firebasestorage.app',
    iosBundleId: 'com.example.eventifySimplified',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvu9gvH2g08k5TcbpQOd_lZctnlrZi9bE',
    appId: '1:807035683294:ios:b8cfbc46a2ac93766b1d4f',
    messagingSenderId: '807035683294',
    projectId: 'eventify-simplified',
    storageBucket: 'eventify-simplified.firebasestorage.app',
    iosBundleId: 'com.example.eventifySimplified',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlqb23RXVkAD1W21TvOVcnm6lL1SmA3Z4',
    appId: '1:807035683294:web:764dad640fe0e45d6b1d4f',
    messagingSenderId: '807035683294',
    projectId: 'eventify-simplified',
    authDomain: 'eventify-simplified.firebaseapp.com',
    storageBucket: 'eventify-simplified.firebasestorage.app',
  );
}
